/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  84532: {
    Funding: {
      address: "0xc314278217Ae8D99D95BdAb3432e174A1a483Ed1",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "gatewayAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
          ],
          name: "ContributionReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "ContributionReceivedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokens",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokensInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
          ],
          name: "RoundCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundCreatedInSecret",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "closeFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "closedFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "contribute",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "contributed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "projectNames",
              type: "string[]",
            },
            {
              internalType: "string[]",
              name: "projectDescriptions",
              type: "string[]",
            },
            {
              internalType: "address payable[]",
              name: "projectAddresses",
              type: "address[]",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "createFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "createdFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "distributeFunding",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "distributedFunding",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "fundingRounds",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "totalContributions",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isOpen",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isDistributed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "gatewayContract",
          outputs: [
            {
              internalType: "contract IGateway",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllRoundIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "roundIds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "s",
              type: "string",
            },
          ],
          name: "stringToUint",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  534351: {
    Funding: {
      address: "0x4CCce31adBEB0703941C25AA3146E105FE054440",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "gatewayAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
          ],
          name: "ContributionReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "ContributionReceivedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokens",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokensInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
          ],
          name: "RoundCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundCreatedInSecret",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "closeFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "closedFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "contribute",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "contributed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "projectNames",
              type: "string[]",
            },
            {
              internalType: "string[]",
              name: "projectDescriptions",
              type: "string[]",
            },
            {
              internalType: "address payable[]",
              name: "projectAddresses",
              type: "address[]",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "createFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "createdFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "distributeFunding",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "distributedFunding",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "fundingRounds",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "totalContributions",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isOpen",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isDistributed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "gatewayContract",
          outputs: [
            {
              internalType: "contract IGateway",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllRoundIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "roundIds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "s",
              type: "string",
            },
          ],
          name: "stringToUint",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  11155111: {
    Funding: {
      address: "0x85C149bEbf45b3E0206c8283b25c1F14F73AEeCF",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "gatewayAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
          ],
          name: "ContributionReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "ContributionReceivedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokens",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokensInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
          ],
          name: "RoundCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundCreatedInSecret",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "closeFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "closedFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "contribute",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "contributed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "projectNames",
              type: "string[]",
            },
            {
              internalType: "string[]",
              name: "projectDescriptions",
              type: "string[]",
            },
            {
              internalType: "address payable[]",
              name: "projectAddresses",
              type: "address[]",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "createFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "createdFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "distributeFunding",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "distributedFunding",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "fundingRounds",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "totalContributions",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isOpen",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isDistributed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "gatewayContract",
          outputs: [
            {
              internalType: "contract IGateway",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllRoundIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "roundIds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "s",
              type: "string",
            },
          ],
          name: "stringToUint",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  11155420: {
    Funding: {
      address: "0x84449Ff21EE6a5D161fA979F06B49327EFce0854",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "gatewayAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
          ],
          name: "ContributionReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "ContributionReceivedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokens",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokensInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
          ],
          name: "RoundCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundCreatedInSecret",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "closeFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "closedFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "contribute",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "contributed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "projectNames",
              type: "string[]",
            },
            {
              internalType: "string[]",
              name: "projectDescriptions",
              type: "string[]",
            },
            {
              internalType: "address payable[]",
              name: "projectAddresses",
              type: "address[]",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "createFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "createdFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "distributeFunding",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "distributedFunding",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "fundingRounds",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "totalContributions",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isOpen",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isDistributed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "gatewayContract",
          outputs: [
            {
              internalType: "contract IGateway",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllRoundIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "roundIds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "s",
              type: "string",
            },
          ],
          name: "stringToUint",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  1313161555: {
    Funding: {
      address: "0x737BE332C0c3e72e2738842a2138051dc0c01A0A",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "gatewayAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contributor",
              type: "address",
            },
          ],
          name: "ContributionReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "ContributionReceivedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokens",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "DistributedTokensInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "projectId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "ProjectCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundClosedInSecret",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
          ],
          name: "RoundCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
          ],
          name: "RoundCreatedInSecret",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "closeFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "closedFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "contribute",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "contributed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256[]",
              name: "projectIds",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "projectNames",
              type: "string[]",
            },
            {
              internalType: "string[]",
              name: "projectDescriptions",
              type: "string[]",
            },
            {
              internalType: "address payable[]",
              name: "projectAddresses",
              type: "address[]",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bool",
              name: "sendToSecret",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "createFundingRound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "createdFundingRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "userAddress",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "payloadHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "routingInfo",
              type: "string",
            },
            {
              components: [
                {
                  internalType: "bytes",
                  name: "user_key",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "user_pubkey",
                  type: "bytes",
                },
                {
                  internalType: "string",
                  name: "routing_code_hash",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "task_destination_network",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "handle",
                  type: "string",
                },
                {
                  internalType: "bytes12",
                  name: "nonce",
                  type: "bytes12",
                },
                {
                  internalType: "uint32",
                  name: "callback_gas_limit",
                  type: "uint32",
                },
                {
                  internalType: "bytes",
                  name: "payload",
                  type: "bytes",
                },
                {
                  internalType: "bytes",
                  name: "payload_signature",
                  type: "bytes",
                },
              ],
              internalType: "struct IGateway.ExecutionInfo",
              name: "info",
              type: "tuple",
            },
          ],
          name: "distributeFunding",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "roundId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "json",
              type: "bytes",
            },
          ],
          name: "distributedFunding",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "fundingRounds",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "curveType",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "totalContributions",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isOpen",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "isDistributed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "gatewayContract",
          outputs: [
            {
              internalType: "contract IGateway",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllRoundIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "roundIds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "s",
              type: "string",
            },
          ],
          name: "stringToUint",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
